### ISSUE TITLE
Duplicate codes for linked list

### ISSUE THREAD

**Issue by FR4NKESTI3N** [OpenGenus/cosmos#3934] opened 2019-02-01 16:53 UTC
there is data_structures/src/list/singly_linked_list, but there is also a code for same problem in data_structures/linked_list/
One of them ought to be removed.

**Comment by rucha174** [comment] 2019-03-08 21:17
Looks like this has been fixed

**Comment by FR4NKESTI3N** [comment] 2019-03-09 12:37
@rucha174 Sorry, I had written wrong file path. Both directories still exist in repo.

**Comment by rucha174** [comment] 2019-03-09 13:32
Is the filename correct?

**Comment by arnavb** [comment] 2019-03-09 13:37
@FR4NKESTI3N @rucha174 If either of you would like to resolve this issue, then by all means go for it! Make sure to reference this issue however.

**Comment by rucha174** [comment] 2019-03-09 15:16
I have sent a PR. Please review it.

**Comment by code-blooded** [comment] 2019-03-23 12:36
Why is this issue still open ? @arnavb @rucha174

**Comment by arnavb** [comment] 2019-03-23 12:54
@code-blooded The old directory isn't completely gone yet. We moved from one file to removing the whole directory, which is pretty much a duplicate of the other one.

**Comment by nisarg1499** [comment] 2019-05-15 08:06
@arnavb Still same code of linked list is seen in both the paths.
Is this issue still open?

**Comment by rucha174** [comment] 2019-05-17 06:52
@arnavb Hello! Should I make the required changes in the code?

**Comment by nitashadhingra** [comment] 2020-03-01 08:01
under GSSoc i would like to contribute @AdiChat

**Comment by shreeya13garg** [comment] 2020-03-23 12:17
I want to contribute in it..I think I would be able to remove the duplicate directory.

**Comment by arnavb** [comment] 2020-03-23 14:22
@shreeya13garg / @nitashadhingra One of you can create a PR and fix this.

**Comment by shreeya13garg** [comment] 2020-03-23 16:14
I have removed the singly linked list from  data_structures/src/list/singly_linked_list to remove duplicates. Should I push it on Github?

**Comment by shreeya13garg** [comment] 2020-03-23 16:22
I have cloned the cosmos repository and committed the changes i.e removing duplicate files now I need permission to push it on github

**Comment by shreeya13garg** [comment] 2020-03-23 17:36
My PR in which I have added the modified code-:https://github.com/shreeya13garg/cosmos_PR 
If there is any error let me know.

**Comment by arnavb** [comment] 2020-03-24 00:07
@shreeya13garg That isn't how you create a pull request. I think you should follow this [guide](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request) and become proficient with git.

**Comment by hanzohasashi33** [comment] 2020-03-29 11:15
Can I take up this issue if it is still open ? @arnavb

**Comment by arnavb** [comment] 2020-03-31 19:21
@hanzohasashi33 Sure. All you have to do is delete the extra folder, basically.

**Comment by hanzohasashi33** [comment] 2020-04-01 03:41
Looks like there is no duplicate folder in data_structures/ for linked list.

**Comment by shreeya13garg** [comment] 2020-04-02 04:42
Yeah, I have already solved it. This issue has been solved.

**Comment by saviourcode** [comment] 2020-07-31 14:36
@arnavb, According to @shreeya13garg, this issue has been resolved, kindly close this issue. It will help others to focus on other pending issues. :smiley:

**Closed** 2020-08-01 20:51 UTC
Labels: bug, good first issue
